version: '3.8'

services:
  db_service:
    image: postgres:14
    container_name: db_service
    ports:
      - "5432:5432"
    environment:      
      - POSTGRES_USER=${POSTGRES_USER}    
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vault_db